# Proxy configuration
systemProp.http.proxyHost=21.0.0.49
systemProp.http.proxyPort=15004
systemProp.http.proxyUser=container_container_01X87gzv8Cf73LpCDYXcF5E8--claude_code_remote--da0167
systemProp.http.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjAwYTAzNTkyLTM0NGQtNGIzZS1iMTU5LWIyZWE3ODI4MWZlYyIsImlhdCI6MTc3NDAzNDE0NywiZXhwIjoxNzc0MDQ4NTQ3LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoiY3NlXzAxSDl3UkxGTkhkTUVZUnNlaWpOUDVSbiIsImNvbnRhaW5lcl9pZCI6ImNvbnRhaW5lcl8wMVg4N2d6djhDZjczTHBDRFlYY0Y1RTgtLWNsYXVkZV9jb2RlX3JlbW90ZS0tZGEwMTY3IiwiZW5mb3JjZV9jb250YWluZXJfYmluZGluZyI6ImZhbHNlIn0.wgTjRj-i6bAPXjJuVGTgoR7sR_aAIT8nDlsZA98VFCO9LtpKwBTM3KRV2YKvPONNxM5qYLkOJiW63JkRp208KA
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.proxyHost=21.0.0.49
systemProp.https.proxyPort=15004
systemProp.https.proxyUser=container_container_01X87gzv8Cf73LpCDYXcF5E8--claude_code_remote--da0167
systemProp.https.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjAwYTAzNTkyLTM0NGQtNGIzZS1iMTU5LWIyZWE3ODI4MWZlYyIsImlhdCI6MTc3NDAzNDE0NywiZXhwIjoxNzc0MDQ4NTQ3LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoiY3NlXzAxSDl3UkxGTkhkTUVZUnNlaWpOUDVSbiIsImNvbnRhaW5lcl9pZCI6ImNvbnRhaW5lcl8wMVg4N2d6djhDZjczTHBDRFlYY0Y1RTgtLWNsYXVkZV9jb2RlX3JlbW90ZS0tZGEwMTY3IiwiZW5mb3JjZV9jb250YWluZXJfYmluZGluZyI6ImZhbHNlIn0.wgTjRj-i6bAPXjJuVGTgoR7sR_aAIT8nDlsZA98VFCO9LtpKwBTM3KRV2YKvPONNxM5qYLkOJiW63JkRp208KA
systemProp.https.nonProxyHosts=localhost|127.0.0.1

# Build performance
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
